# Generated by Django 5.1.7 on 2025-03-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='Booking',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='Menu',
        ),
    ]
